### ISSUE TITLE
Fix e2e testing

### ISSUE THREAD

**Issue by layik** [tgve/eatlas-template#55]
- fix `Test (inc e2e)` job to test against `develop` branch of `tgvejs`, rather than version installed from node
  - [x] `checkout` action for `tgvs` needs `repository: tgve/tgvejs`
  - in `tgvejs`:
    - [x] `yarn install` (for e.g. `babel`)
    - [x] `yarn link` to register `@tgve/tgvejs` 
    - [x] `yarn dist` (to ensure module exists)
  - in `app`:
    - [x] `yarn link @tgve/tgvejs` to symlink to local `tgvejs`
    - [x] `yarn build-local`
  - [x] separate `Test` and `Test (e2e)` steps
  - [x] `Test` failing with “Invalid hook call” (React error 321)
    - [x] `yarn test` should not run e2e tests – only `yarn test:e2e`
    - [x] `yarn purge-tgvejs-react` to remove duplicate copy of React
      - [x] :x: Cannot find module ‘react’ from ‘index.js’ (from `/tgvejs/dist/index.js`) – just delete `App.test.js`
- [x] enable `dumpio` in `puppeteer.launch`
- [x] identify conditions of build failure: fails on `release` branch only, after “Upgrade tgve.js” step
- [x] `reset –hard` to undo “Upgrade tgve.js” step on `puppeteer-experiment `branch 
- [x] delete “Upgrade tgve.js” and force merge to `release` 
- [x] Replace “Set homepage” step by appropriate use of `PUBLIC_URL=` in `Build [release]` step 
- [x] extract “Build [local]“ step from “Test (e2e)”
- [x] fix `Test (inc e2e)` job to test against `develop` branch of `tgvejs`, rather than version installed from node
  - [x] `Test (e2e)` failing with “Invalid hook call” (React error 321)
    - [x] switch from `url.pathToFileURL(“build/index.html”)` to `“http://localhost:3000/app”` 
- [x] e2e still failing locally
  - [x] CSS class `side-pane-header` no longer exists (uh?) – rehash all selectors for now
  - [x] `.side-panel-body-content > div > span` selector no longer works in last test
- [x] test startup and shutdown
  - [x] add `yarn start &` in `app` to `Test (e2e)` step :x: first test times out because of web server startup 
  - [x] [start web server and wait until started](https://stackoverflow.com/questions/63192833/sequential-npm-script-after-react-scripts-start) using `wait-on` and `concurrently`
  - [x] `yarn start` doesn’t return and causes “Test (e2e)” to hang
    - [x] run `concurrently` with `--kill-others –success last` :x: still fails with exit code
    - [x] swap arguments and use `--success first`

**Comment by layik** [comment]
It [e2e] works only by splitting it, should work in one file too!
https://github.com/tgve/app/commit/3f8b731819ed403c2bf5aa2645d9a77f872bdb5a

**Comment by layik** [comment]
Hi @rolyp, just noticed that above commit passed in what is `e2e.yml` in branch issue55 but this one fails
https://github.com/tgve/app/commit/7d0771ea0c67f24b3d192358c66c0cc0b4f67ca2

I doubt it is anything to do with macOS? I will ask for your review of the PR.

**Comment by rolyp** [comment]
@layik Looks like the e2e tests go wrong only on `release`, i.e. when the `Upgrade tgve.js` job (which looks a bit weird) runs. I'll have a look at this in more detail tomorrow.

**Comment by rolyp** [comment]
Some notes:

1. It’s important to run with `dumpio` enabled in `puppeteer.launch`. Timeouts because no element matches a selector are often masked by generic `ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed`. By default Puppeteer absorbs any console output from the web app.

1. Testing against the file protocol and build directory seemed to cause React error 321 (duplicate copy of React) error to resurface, even with the script to purge React from the copy of `tgvejs` in `app`. This was resolved by switching back to a webserver and regular URLs.

1. The “Upgrade tgve.js” step was also causing problems, and anyway seemed hard to justify. The decision to upgrade `tgve.js` should be taken by the user, not automatically by a build script, and such a change shouldn’t be commited before tests have been run. Removed this step.

1. Removed the “Set homepage” step and instead do this in the Build [release] step via `PUBLIC_URL`.

1. Fixed the problem where the tests were running against the node-installed version of `tgvejs`, rather than the version checked out in GitHub Actions. **The `app` tests now run against the `develop` branch of `tgvejs`.** In other words, pushing to `tgvejs` may invalidate the tests on `app`, although that won’t become apparent until the next build of `app`.

1. Existing `App.js.test` script wasn’t contributing much. Deleted.

1. Ensuring the e2e tests start up properly (without the webserver startup causing the first test to time out) and shutdown properly is done using `concurrently` and `wait-on` (see the [`yarn test`](https://github.com/tgve/app/blob/release/.github/workflows/build-deploy.yml) script for more information).

**Comment by layik** [comment]
All noted. I think as said on Slack, the e2e needs to move under tgvejs.
